---
- hosts: all
  become: true
  vars:
      - pipe_dump_stub: ngts_pipe.sql.bz2
      - ops_dump_stub: ngts_ops.sql.bz2
      - db_user: www
  handlers:
      - name: restart apache
        service:
            name: apache2
            state: restarted
        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

      - name: restart apache
        service:
            name: httpd
            state: restarted
        when: ansible_distribution == 'CentOS'

  tasks:
      - name: Install required packages (Debian/Ubuntu)
        apt:
            name: "{{ item }}"
            update_cache: yes
            cache_valid_time: 86400
        with_items:
            - mysql-server
            - mysql-client
            - apache2
            - apache2-doc
            - php5
            - php5-mysql
            - libapache2-mod-php5
            - python-mysqldb
            - multitail
            - tree
        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

      - name: Install required packages (CentOS)
        yum:
            name: "{{ item }}"
            update_cache: yes
        with_items:
            - mariadb
            - mariadb-server
            - httpd
            - php
            - php-mysql
            - MySQL-python
            - tree
        when: ansible_distribution == 'CentOS'

      - name: Enable mysql (Debian)
        service:
            name: mysql
            enabled: yes
            state: started
        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

      - name: Enable mysql (CentOS)
        service:
            name: mariadb
            enabled: yes
            state: started
        when: ansible_distribution == 'CentOS'

      - name: Enable apache (Debian)
        service:
            name: apache2
            enabled: yes
            state: started
        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

      - name: Enable apache (CentOS)
        service:
            name: httpd
            enabled: yes
            state: started
        when: ansible_distribution == 'CentOS'

      - name: Add the mysql user
        mysql_user:
            name: "{{ db_user }}"
            host: localhost
            state: present
            password: password
            priv: "*.*:ALL"

      - name: Copy the ngts_pipe database dump
        copy:
            src: "{{ pipe_dump_stub }}"
            dest: /tmp

      - name: Copy the ngts_ops database dump
        copy:
            src: "{{ ops_dump_stub }}"
            dest: /tmp

      - name: Add the ngts_pipe database
        mysql_db:
            name: ngts_pipe
            state: import
            target: /tmp/{{ pipe_dump_stub }}

      - name: Add the ngts_ops database
        mysql_db:
            name: ngts_ops
            state: import
            target: /tmp/{{ ops_dump_stub }}

      - name: Ensure the host is known as ngtsdb
        lineinfile:
            name: /etc/hosts
            line: '127.0.0.1    localhost ngtsdb'
            insertafter: EOF
            owner: root
            group: root
            mode: 0644

      - name: Remove the default apache config file (Debian)
        file:
            name: "{{ item }}"
            state: absent
        with_items:
            - /etc/apache2/sites-enabled/000-default.conf
            - /etc/apache2/sites-available/000-default.conf
        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
        notify: restart apache

      - name: Remove the default apache config file (CentOS)
        template:
            src: centos-welcome.conf
            dest: /etc/httpd/conf.d/welcome.conf
            owner: root
            group: root
        when: ansible_distribution == 'CentOS'
        notify: restart apache

      - name: Install the custom apache config (Debian)
        template:
            src: 001-ngtsqa.conf
            dest: /etc/apache2/sites-enabled/001-ngtsqa.conf
            owner: root
            group: root
        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
        notify: restart apache

      - name: Install the custom apache config (CentOS)
        template:
            src: 001-ngtsqa.conf
            dest: /etc/httpd/conf.d/001-ngtsqa.conf
            owner: root
            group: root
        when: ansible_distribution == 'CentOS'
        notify: restart apache
